### ISSUE TITLE
Leave game from lobby

### ISSUE THREAD

**Issue by kukshalkanishka** [STEP-tw/uno-skyrus#25]
As a Player

I want to leave the game while waiting for other player to join

So that I may join/host another game.

**Acceptance Criteria**

- [ ] Criteria 1
  - Given I have joined/hosted the game.
  - When I am waiting for other players to join
  - Then there should be a way of leaving the game from the lobby.

- [ ] Criteria 2
  - Given i was waiting for other players to join
  - When I left the game
  - Then other players should get notified about it.

- [ ] Criteria 3
  - Given i was waiting for other players to join
  - When I left the game
  - Then my name from the card in lobby, should be replaced with the waiting icon.

**Comment by rahulmadaan** [comment]
merged with leave game story [#22]
